
./inventory_manager: ./inventory_manager.cpp ./inventory.cpp ./product.cpp ./main.cpp ./order.cpp
	g++ -I . ./inventory_manager.cpp ./inventory.cpp ./product.cpp ./order.cpp ./main.cpp -o ./inventory_manager